#  MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/watchtower?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Fingerling1010@#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#  Polling config
watchtower.target.url=http://localhost:9090/health
watchtower.poll.interval=10000

#  Simulator port
watchtower.simulator.port=9090

#  Main server port
server.port=8080

# ?? Email alerting ????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ofilitobe@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

watchtower.alert.email=ofilitobe@gmail.com
watchtower.alert.latency.threshold=2000